105 fix profilescreen
Davod0/App-Development-Household-Application pull request #117
Opened 2024-10-28 14:24 UTC by LiamGlamheden

2024-10-28 15:01 UTC, mrKornelius requested changes
Läs issue beskrivningen :)

2024-10-29 13:13 UTC, mrKornelius commented on screens/ProfileScreen.tsx
> +  const [email, setEmail] = useState<string | null>(null);
du borde använda 
const user = useAppSelector(selectCurrentUser);
(sen ligger email som user.email) du ska inte sätta den som ett state och det kommer alltid finnas en user när man är på profilsidan så sätt user!email om den gnäller att det kan vara null/undefined.

2024-10-29 13:16 UTC, LiamGlamheden commented on screens/ProfileScreen.tsx
> +  const [email, setEmail] = useState<string | null>(null);
Si

2024-10-29 13:24 UTC, LiamGlamheden commented on screens/ProfileScreen.tsx
> +  useEffect(() => {
Jag hade problem att få den att fungera med min handle när den var där. Men jag kan flytta tillbaks den om du tycker så.

2024-10-29 13:26 UTC, mrKornelius commented on screens/ProfileScreen.tsx
> +  if (!member) {
tänk på hur du har kommit till denna sidan.

1. Först måste man logga in (user kommer alltid finnas)
2. Sedan ska man välja ett hushåll (selectedHousehold kommer alltid finnas + en member för dig på hushållet)
3. Sedan kan man komma till profilsidan (och då kommer alltid member finnas, så du kommer inte behöva kolla det basically.)

2024-10-29 14:47 UTC, LiamGlamheden commented on screens/ProfileScreen.tsx
> +  useEffect(() => {
Du hade rätt! det funkade utmärkt att ha den i Rootstack

2024-10-30 00:31 UTC, LiamGlamheden commented
Hej,

Jag har kollat och fixat de här kommentarerna. Kolla gärna så fort du har tid 😁

2024-10-30 08:27 UTC, mrKornelius approved these changes
nice 👍🏻

2024-10-30 08:28 UTC, merged